parser: babel-eslint
env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends:
  - 'eslint:recommended'
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - { "avoidEscape": true }
  semi:
    - error
    - always
  no-console:
    - off
  keyword-spacing:
    - error
    - { before: true, after: true }
  object-curly-spacing:
    - error
    - always
