language: node_js
node_js:
  - '6'

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - npm run lint

notifications:
  email: false