language: node_js
node_js:
  - 6
  - 7
  - 8

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn global add lerna@2.2.0
  - lerna bootstrap --hoist

script:
  - yarn test

notifications:
  email: false
