defaults: &defaults
  docker:
    - image: circleci/node:8

aliases:
  - &restore-cache
      keys:
        - dependency-cache-{{ checksum "package.json" }}

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run:
          name: "Install Dependencies"
          command: |
            yarn
            ./node_modules/.bin/lerna bootstrap
      - save-cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules/
            - ./packages/react-native-version-check/node_modules/
            - ./packages/react-native-version-check-expo/node_modules/
      - run:
          name: "Test"
          command: |
            yarn test
      - run:
          name: "Generate Coverage Report"
          command: |
            yarn test:coverage
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  test:
    jobs:
      - test
